// Generated by CoffeeScript 1.4.0
(function() {
  var ObjectId, bson;

  bson = require("bson");

  ObjectId = bson.ObjectId;

  module.exports.isObjectId = function(nameOrId) {
    if (!nameOrId) {
      return false;
    }
    nameOrId = nameOrId.toString();
    if (nameOrId.length !== 24) {
      return false;
    }
    try {
      return !!(new ObjectId(nameOrId));
    } catch (e) {
      return false;
    }
  };

}).call(this);
